### PR TITLE
Updated the quality control plots

### PR DESCRIPTION
**Pull request by pakiessling**
To show in how many different cells individual genes are expressed.

Discussed in https://github.com/scverse/squidpy/issues/629

### CODE REVIEW

**Comment by giovp** [comment]
fantastic work @pakiessling ! this is very useful contribution and I'm sure it'll make it easier for users to understand this type of pre-processing.

In case you feel like it's doable, would you consider updating the same plot for the nanostring vignette? The file in your fork is here https://github.com/pakiessling/squidpy_notebooks/blob/merfish_tutorial/docs/source/external_tutorials/tutorial_nanostring.ipynb

let me know and in case you rather skip it I'll merge this PR right away.

Thanks a lot for this contribution!

**Comment by pakiessling** [comment]
@giovp Sure I can give nanostrings a shot.

In general I have some Ideas on how I could improve the tutorials, if you would be up for that.

Change the deprecated sns.distplot to sns.histplot, explain the QC process a bit more, add some more details and references for Centrality score ect...

**Comment by giovp** [comment]
that sounds fantastic! I'd be really curious to see these type of improvements, please go ahead!
You could do it here, or on a separate PR as you wish. If you'd like to chat more or asking anything specific I'd also suggest to join our scverse zulip (see link here https://scverse.org/join/ ).

**Comment by giovp** [comment]
hi @pakiessling , we are planning to have new release next month and I'd love to include these types of improvements in 1.3.0 , let me know if you are still interested otherwise no problem we'll include this as is!

**Comment by pakiessling** [comment]
@giovp Hi Giovanni, I am currently on holiday, but will be back & focusing on this next week. I am very interested in improving the documentation further.

I know most about Merfish, since this is the technology I have access too, but I assume at least the QC steps will be similar for other technologies?

**Comment by giovp** [comment]
@pakiessling any update on this? we are in full swing for new release and we'd like to include some of these changes. @LLehner  are doing some notebooks conversions to ease up current notebooks CI. Let me know if the above mentioned are still in scope for you and otherwise would go on and merge this as is and you can push changes to another PR.

**Comment by pakiessling** [comment]
Hi Giovanni, sorry about this. I am unfortunately stuck in Corona Quarantine without access to my work Pc. Let’s just stay with this PR for now.

I will open another PR for further improvements when I get back to work.

From: Giovanni Palla ***@***.***>
Reply to: scverse/squidpy_notebooks ***@***.***>
Date: Friday, 17. February 2023 at 08:39
To: scverse/squidpy_notebooks ***@***.***>
Cc: "Kießling, Paul" ***@***.***>, Mention ***@***.***>
Subject: Re: [scverse/squidpy_notebooks] Updated the quality control plots (PR #110)


@pakiessling<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpakiessling&data=05%7C01%7C%7Cfeef6c86c77a4a7f5be808db10ba182b%7C5a6d5ee56edf4a26ba93f5872dbb9614%7C0%7C0%7C638122163681002644%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FsbFwnlSbG%2BioWHAaVXxXBMcFKm2n1uCeSXjuuKeKlo%3D&reserved=0> any update on this? we are in full swing for new release and we'd like to include some of these changes. @LLehner<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLLehner&data=05%7C01%7C%7Cfeef6c86c77a4a7f5be808db10ba182b%7C5a6d5ee56edf4a26ba93f5872dbb9614%7C0%7C0%7C638122163681002644%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=W7Dye5xtlPeSM8rylW%2F%2BslJ2qTJPSQRPIWM0nHE59aY%3D&reserved=0> are doing some notebooks conversions to ease up current notebooks CI. Let me know if the above mentioned are still in scope for you and otherwise would go on and merge this as is and you can push changes to another PR.

**Comment by pakiessling** [comment]
Hi @giovp I improved the tutorials for the QC of Merfish, Xenium and Nanostrings. They make a bit more sense now. Let me know what you think.

**Comment by pakiessling** [comment]
@LLehner thanks for fixing my spelling 🙈

**Comment by LLehner** [comment]
Thank you for the improved tutorials and the PR @pakiessling!

**Pull request merged**
